### ISSUE TITLE
server not found: no server available

### ISSUE THREAD

**Issue by YannMoisan** [etaty/rediscala#205]
I'm using Redis in cluster mode.

Some write commands fail with the following error

```
java.lang.RuntimeException: server not found: no server available
	at redis.RedisCluster$$anonfun$send$2.apply(RedisCluster.scala:161)
	at redis.RedisCluster$$anonfun$send$2.apply(RedisCluster.scala:161)
```

**Comment by CharlesAHunt** [comment]
I also have this issue, here is my connection information:

getClusterSlots ->     Map()

info ->     # Server
redis_version:3.2.10
redis_git_sha1:0
redis_git_dirty:0
redis_build_id:0
redis_mode:cluster
os:Amazon ElastiCache
arch_bits:64
multiplexing_api:epoll
gcc_version:0.0.0
process_id:1
run_id:e2fc2c6a9a39dbe653f0cbc3fb734498031ee38c
tcp_port:6379
uptime_in_seconds:7263021
uptime_in_days:84
hz:10
lru_clock:1493388
executable:-
config_file:-

# Clients
connected_clients:5
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:4868568
used_memory_human:4.64M
used_memory_rss:7254016
used_memory_rss_human:6.92M
used_memory_peak:4994896
used_memory_peak_human:4.76M
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:6501171200
maxmemory_human:6.05G
maxmemory_policy:volatile-lru
mem_fragmentation_ratio:1.49
mem_allocator:jemalloc-4.0.3

# Persistence
loading:0
rdb_changes_since_last_save:8134763
rdb_bgsave_in_progress:0
rdb_last_save_time:1520957023
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:556
total_commands_processed:27159031
instantaneous_ops_per_sec:3
total_net_input_bytes:887641730
total_net_output_bytes:21850496874
instantaneous_input_kbps:0.11
instantaneous_output_kbps:3.33
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:3786768
keyspace_misses:1151968
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:2176.62
used_cpu_user:3571.62
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:1

# Keyspace
db0:keys=4,expires=0,avg_ttl=0

redisServers ->     List(RedisServer(***.cache.amazonaws.com,6379,None,Some(0)))
getClusterAndConnection:     None
name:     RedisClientPool
redisServerConnections:     Map(RedisServer(***.cache.amazonaws.com,6379,None,Some(0)) -> RedisConnection(Actor[akka://redis-system/user/RedisClientPool-$a#115

**Comment by Earth-43** [comment]
I have also faced the same issue , the workaround is to give actual endpoint of nodes like 
`List(RedisHost("redis-public.cache.amazonaws.com", 6379), RedisHost("redis-public.cache.amazonaws.com", 6379) )` its with play redis 
but here the main issue is that if any proxy is available in between( **through haproxy** ) then it is not working getting same error . any suggestion will help !!!

**Comment by gr1ev0us** [comment]
It caused by filtering available redis host with cluster map. [here](https://github.com/etaty/rediscala/blob/master/src/main/scala/redis/RedisCluster.scala#L65) 

My recommendation is to use direct redis address instead of hosts.

**Comment by 2690522020** [comment]
I also have this issue, Some write commands fail with the following error
java.lang.RuntimeException: server not found: no server available
        at redis.RedisCluster.$anonfun$send$2(RedisCluster.scala:158)
        at scala.Option.getOrElse(Option.scala:138)
        at redis.RedisCluster.send(RedisCluster.scala:158)
        at play.api.cache.redis.connector.RedisCommandsCluster$$anon$2.play$api$cache$redis$connector$RedisRequestTimeout$$super$send(RedisCommands.scala:106)
        at play.api.cache.redis.connector.RedisRequestTimeout.continue$2(RequestTimeout.scala:74)
        at play.api.cache.redis.connector.RedisRequestTimeout.$anonfun$send$4(RequestTimeout.scala:76)
        at scala.Option.fold(Option.scala:175)
        at play.api.cache.redis.connector.RedisRequestTimeout.send(RequestTimeout.scala:76)
        at play.api.cache.redis.connector.RedisRequestTimeout.send$(RequestTimeout.scala:72)
        at play.api.cache.redis.connector.RedisCommandsCluster$$anon$2.send(RedisCommands.scala:106)
